package com.example.userdaniel.ironkingdoms.DrawerListFragments;

import android.app.Activity;
import android.app.Fragment;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ListView;

import com.example.userdaniel.ironkingdoms.Adapters.CareerAdapter;
import com.example.userdaniel.ironkingdoms.Models.Career;
import com.example.userdaniel.ironkingdoms.R;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Locale;

/**
 * Created by UserDaniel on 3/1/16.
 */
public class CareersFragment extends Fragment {


    private OnFragmentInteractionListener mListener;
    private ArrayList<Career> arrayList = new ArrayList<>();
    private CareerAdapter abilityAdapter;


    /**
     * Mandatory empty constructor for the fragment manager to instantiate the
     * fragment (e.g. upon screen orientation changes).
     */
    public CareersFragment() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.searchable_list1, container, false);

        String[][] abilities = {{"Alchemist","None","Grenadier and Poison Resistance","","Hand Weapon 1 and Thrown Weapon 1","Alchemy 1 and Medicine 1","","","50 gc, alchemist's leather, gas mask, traveling alchemist's kit, any five alchemical grenades, and a grenadier's bandolier.","Bomber, Brew Master, Fast Cook, Field Alchemist, Fire in the Hole!, Free Style, Grenadier, Poison Resistance","Connections (Alchemical Order)","Hand Weapon 2, Thrown Weapon 4, Unarmed Combat 2","Alchemy 4, Craft 4 (any), Forgery 2, General Skills 4, Medicine 4, Negotiation 4, Research 4",""},
        {"Arcane Mechanik","Gifted","Inscribe Formulae","","Hand Weapon 1 or Rifle 1","Craft (gunsmithing) 1, Craft (metalworking) 1, and Mechanikal Engineering 1","Arcantrik Bolt and Polarity Shield","","50 gc and a rune etching kit. The character also begins the game with a mechanika weapon or suit of armor worth up to 750 gc, including the device's housing, power source, and rune plate.","'Jack Marshal, Ace Commander, Arcane Engineer, Drive: Assault, Drive: Pronto, Inscribe Formulae, Resourceful, Steamo","Connections (Mechaniks organization)","Hand Weapon 2, Light Artillery 2, Rifle 2","Command 1, Craft 4 (any), Cryptography 3, General Skills 4, Mechanikal Engineering 4, Negotiation 2, Research 3.","Spells"},
        {"Arcanist","Gifted","Great Power","","","Lore (Arcane) 1 and Research 1","Arcane Bolt, Aura of Protection, Light in the Darkness","A character who chooses Arcanist as one of his two starting careers gains the Rune Reader Gifted archetype benefit.","75 gc","Arcane Defenses, Arcane Scholar, Great Power, University Education","Connections (Magical Order)","––","Craft 2 (any), Etiquette 2, General Skills 4, Negotiation 2, Oratory 2, Research 4", "Spells"},
        {"Aristocrat","Human, Starting Career","Good Breeding, Language (any), Privilege","Connections (Nobility)","Hand Weapon 1 and the choice of one other: Archery 1, Pistol 1, or Rifle 1","Command 1 and Etiquette 1","","A character who chooses Aristocrat as one of his two starting careers gains 50 gc each month from his family holdings.","200 gc","Advisor, Appraise, Battle Plan: Call to Action, Expert Rider, Good Breeding, Language, Natural Leader, Poison Resistance, Privilege, Rallying Cry, Swift Rider","Connections (any)","Archery 2, Hand Weapon 3, Lance 3, Pistol 2, Rifle 3","Bribery 4, Command 4, Cryptography 2, Deception 4, Etiquette 4, General Skills 4, Law 4, Negotiation 4, Oratory 4, Seduction 4", ""},
        {"Bounty Hunter","None","Binding and Take Down","","Choose two: Crossbow 1, Hand Weapon 1, Pistol 1, Rifle 1, Unarmed Combat 1","Detection 1, Intimidation 1, Rope Use 1, Tracking 1","","","75 gc","Binding, Crossbowman, Head-Butt, Language (Five Cant), Pursuit, Roll With It, Take Down, Waylay","Connections (any)","Crossbow 3, Hand Weapon 2, Pistol 2, Rifle 3, Unarmed Combat 4","Bribery 2, Deception 2, Disguise 2, General Skills 4, Interrogation 2, Law 2, Negotiation 4, Rope Use 4, Sneak 3, Streetwise 4, Tracking 4", ""},
        {"Cutthroat","None","Anatomical Precision, Backstab, and Prowl","","Hand Weapon 1, and one other: Crossbow 1, Thrown Weapon 1, or Unarmed Combat 1","Intimidation 1, Sneak 1, and Streetwise 1","","","75 gc","Anatomical Precision, Backstab, Blood Spiller, Camouflage, Chain Attack: Bleed Out, Fast Draw, Language (Five Cant), Prowl, Specialization (Assassin Blade), Strangler, Two-Weapon Fighting, Waylay","Connections (criminal)","Crossbow 2, Hand Weapon 4, Thrown Weapon 3, Unarmed Combat 3","General skills 4, Interrogation 2, Sneak 4, Streetwise 4", ""},
        {"Duelist","None","Parry and Riposte","","Hand Weapon 1 and Pistol 1","Gambling 1, Intimidation 1, and Jumping 1","","","75 gc","Acrobatics, Fast Draw, Gunfighter, Parry, Precision Strike, Quick Work, Riposte, Roll With It,Two-Weapon Fighting.","––","Hand Weapon 4, Pistol 4, Thrown Weapon 3, Unarmed Combat 2","Etiquette 2, General skills 4, Law 2, Oratory 2, Seduction 3, Streetwise 2", ""},
        {"Explorer","None","Big Game Hunter, Language (any), Port of Call","Connections (Patron)","Choose one: Archery 1, Hand Weapon 1, Pistol 1, or Rifle 1","Detection 1, Medicine 1, Navigation 1, and Survival 1","","A character who chooses Explorer as one of his two starting careers gains 25 gc each month from his patron for as long as he continues to explore new regions, report back regularly, and bring his patron occasional gifts from exotic places.","150 gc, map case, and spyglass","Battle Plan: Reconnaissance, Big Game Hunter, Disease Resistance, Expert Rider, Language, Natural Leader, Poison Resistance, Port of Call, Signal Language, Swift Rider","Connections (wealthy patrons), Connections (isolated tribe or people)","Archery 2, Crossbow 2, Hand Weapon 2, Pistol 2, Rifle 3, Thrown Weapon 2, Unarmed Combat 2","Command 4, Craft (any) 2, Cryptography 2, Etiquette 2, General Skills 4, Medicine 2, Navigation 4, Negotiation 4, Rope Use 4, Survival 4", ""},
        {"Fell Caller","Trollkin","Fell Call: Signal Call and Fell Call: Sonic Blast","","Great Weapon 1 or Hand Weapon 1","Command 1, Fell Callng 2, Lore (Trollkin) 1, and Oratory 1","","","75 gc","Battle Plan: Call to Action, Fell Call: Cacophony, Fell Call: Call of Defiance, Fell Call: Ground Shaker, Fell Call: Heroic Ballad, Fell Call; Reverberation, Fell Call: Signal Call, Fell Call: Sonic Blast, Legacy of Bragg, Natural Leader","Connections (Kriel)","Great Weapon 3, Hand Weapon 3, Thrown Weapon 3, Unarmed Combat 3","Command 4, Fell Calling 4, General Skills 4, Oratory 4, Seduction 2", ""},
        {"Field Mechanik","None","'Jack Marshal, Bodge, and Hit the Deck!","","Hand Weapon 1 or Pistol 1","Command 1, Craft (metalworking) 1, and Mechanikal Engineering 1","","","25 gc, mechanik's tool kit, and a light laborjack with up to 200 gc of weapons.","’Jack Marshal, Ace Commander, Bodge, Dodger, Drive: Ancillary Attack, Drive: Assault, Drive: Off Road, Drive: Pronto, Hit the Deck!, Iron Sentinel, Scrounge, Steamo, Tune Up","Connections (mechaniks organization)","Hand Weapon 2, Pistol 2","Command 3, Craft 4 (any), General Skills 4, Mechanikal Engineering 4, Negotiation 3", ""},
        {"Gun Mage","Gifted","Craft Rune Shot and Fast Reload","","Pistol 1 or Rifle 1","Detection 1 and Intimidation 1","Rune Shot: Accuracy, Rune Shot: Brutal, Rune Shot: Thunderbolt","","25 gc, ammo bandolier, magelock pistol or rifle (with powder and ten rounds of ammunition), and a rune shot casting kit","Arcane Precision, Craft Rune Shot, Fast Draw, Fast Reload, Gunfighter, Keen Eyed","Connections (gun mage order)","Pistol 4, Rifle 4","General Skills 4, Seduction 2", "Spell"},
        {"Highwayman","None","Ambush and Saddle Shot","","Hand Weapon 1 and choose one: Archery 1, Crossbow 1, or Pistol 1","Animal Handling 1, Detection 1, Intimidation 1, and Riding 1","","","75 gc, mask, riding horse, and tack","Ambush, Appraise, Binding, Expert Rider, Fast Draw, Fast Reload, Light Cavalry, Prowl, Ride-By Attack, Saddle Shot, Swift Hunter, Swift Rider, Traceless Path, Two-Weapon Fighting, Waylay","Connections (criminal)","Archery 3, Crossbow 3, Hand Weapon 3, Pistol 3, Unarmed Combat 3","Bribery 2, Deception 3, Disguise 2, General Skills 4, Interrogation 2, Negotiation 4, Rope Use 4, Seduction 4, Sneak 4, Survival 2", ""},
        {"Investigator","None","Astute and Language (any)","","Hand Weapon 1 or Pistol 1","Detection 1, Forensic Science 1, Interrogation 1, Law 1, Medicine 1, and Sneak 1","","A character who chooses Investigator as one of his two starting careers gains the Hyper Perception Intellectual archetype benefit.","100 gc","Anatomical Precision, Astute, Iron Will, Language, Prowl, Signal Language, Truth Reader","Connections (any)","Hand Weapon 2, Pistol 2, Unarmed Combat 2","Cryptography 4, Deception 4, Etiquette 2, Forensic Science 4, General Skills 4, Interrogation 4, Law 4, Medicine 2, Negotiation 3, Research 4, Sneak 4, Streetwise 4", ""},
        {"Iron Fang","Human (Khadoran), Starting Career, and Restricted 2nd Career","Fast Rearm (Blasting Pike) and Specialization (Blasting Pike)","Connections (Khadoran military)","Great Weapon 1 and Shield 1","Command 1 and Survival 1","","A character starting with the Iron Fang career must choose between Aristocrat, Military Officer, Soldier, or Warcaster for his second career.","25 gc, blasting pike (with a spear head and ten blasting heads), Iron Fang full plate, shield","Defensive Line, Fast Arm (Blasting Pike), Hyper Awareness, Load Bearing, Precision Strike, Relentless Charge, Rock Solid, Specialization (Blasting Pike), Swift Rider","Connections (Khadoran military)","Great Weapon 4, Lance 4, Shield 4, Unarmed Combat 3","Command 4, General Skills 4, Survival 2", ""},
        {"Knight", "Human or Iosan", "Cleave and Defender", "Connections (Knighty order)", "Great Weapon 1, Hand Weapon 1, and Shield 1", "Command 1, Etiquette 1, and Lore (knightly order) 1", "", "", "100 gc", "Cavalry Charge, Cleave, Combat Rider, Defender, Defensive Line, Expert Rider, Iron Will, Load Bearing, Natural Leader, Precision Strike, Press the Attack, Relentless Charge, Ride-By Attack, Shield Slam", "Connections (knightly order)", "Great Weapon 4, Hand Weapon 4, Lance 4, Shield 4, Unarmed Combat 3", "Command 4, Etiquette 2, General Skills 4, Law 2", ""},
        {"Mage Hunter","Iosan","Arcane Assassin and Iron Will","Connections (Retribution of Scyrah)","Hand Weapon 1, and either Archery 1 or Crossbow 1","Climbing 1, Jumping 1, Sneak 1, and Tracking 1","","","75 gc","Arcane Assassin, Camouflage, Crackshot, Crossbowman, Fast Draw, Fast Reload, Iron Will, Mage Killer, Parry, Quick Work, Shadow Magic, Traceless Path","Connections (Retribution of Scyrah)","Archery 4, Crossbow 4, Hand Weapon 4, Thrown Weapon 2","Deception 2, Disguise 2, General Skills 4, Rope Use 3, Sneak 4, Survival 2, Tracking 4", ""},
        {"Man-At-Arms","None","Defensive Line and Shield Guard","","Great Weapon 1 and Shield 1, and either Hand Weapon 1 or Pistol 1","Command 1 and Detection 1","","","100 gc","Bodyguard, Cleave, Defensive Line, Girded, Iron Will, Load Bearing, Retaliatory Strike, Set Defense, Shield Guard, Shield Slam, Specialization (Halberd), Specialization (Spear)","Connections (employer)","Great Weapon 4, Hand Weapon 3, Pistol 3, Shield 4, Unarmed Combat 3","Command 3, Craft (metalworking) 2, General Skills 4", ""},
        {"Military Officer","None","Battle Plan: Call to Action, Natural Leader, and Team Leader","","Hand Weapon 1 and either Great Weapon 1 or Pistol 1","Command 1, Medicine 1, and Navigation 1","","","100 gc and officer's uniform","’Jack Marshal, Ace Commander, Battle Commander, Battle Plan: Call to Action, Battle Plan: Coordinated Strike, Battle Plan: Desperate Pace, Battle Plan: Go to Ground, Cavalry Charge, Defender, Drive: Assault, Drive: Pronto, Expert Rider, Good Breeding, Natural Leader, Port of Call, Ride-By Attack, Saddle Shot, Signal Language, Team Leader","Connections (mercenary company or kingdom’s military)","Great Weapon 4, Hand Weapon 4, Pistol 4","Command 4, Cryptography 4, Etiquette 4, General Skills 4, Interrogation 4, Law 4, Medicine 4, Navigation 4, Oratory 4", ""},
        {"Pirate","None","Gang, Steady, and Specialization (Cutlass)","","Hand Weapon 1, and either Pistol 1 or Thrown Weapon 1","Climbing 1, Intimidation 1, Sailing 1, and Swimming 1","","","75 gc","Binding, Disease Resistance, Gang, Gunfighter, Head-Butt, Languages, Port of Call, Quick Work, Specialization (Cutlass), Steady, Sucker!, Waylay","Connections (pirate crew)","Hand Weapon 3, Light Artillery 2, Pistol 3, Rifle 2, Thrown Weapon 3, Unarmed Combat 3","Command 2, Deception 3, General Skills 4, Navigation 4, Negotiation 2, Rope Use 4, Sailing 4", ""},
        {"Pistoleer", "None", "Fast Draw, Gunfighter, and Return Fire", "", "Pistol 1", "Detection 1, Intimidation 1, and Sneak 1", "", "", "50 gc, an ammo bandolier, and either a hand cannon (with ammunition for ten shots) or a pair of repeating pistols (each with one ammo wheel and ammunition for ten shots)", "Chain Attack: Pin Down, Dodger, Fast Draw, Fast Reload, Gunfighter, Return Fire, Swift Hunter, Targeteer, Two-Weapon Fighting", "––", "Pistol 4", "Craft (gunsmithing) 4, General Skills 4, Sneak 3", ""},
        {"Priest Of Menoth","Human, Gifted, Worship of Menoth","Dispel","Connections (Menite temple)","Great Weapon 1 or Hand Weapon 1","Lore (Menite Faith) 1 and Oratory 1","Guided Blade, Ignite, and Immolation","","75 gc","Choir, Language, Natural Leader, Rallying Cry, University Education","Connections (character’s church)","Great Weapon 3, Hand Weapon 3, Shield 2","Command 2, Cryptography 2, Etiquette 4, General Skills 4, Law 4, Medicine 4, Negotiation 4, Oratory 4, Research 4", "Spells"},
        {"Priest Of Morrow","Human, Gifted, Worship of Morrow","Empower","Connections (Morrowan Churge)","Great Weapon 1 or Hand Weapon 1","Lore (Morrowan Faith) 1 and Medicine 1","Blade of Radiance, Solovin's Boon, and True Sight","","75 gc","Choir, Language, Natural Leader, Rallying Cry, University Education","Connections (character’s church)","Great Weapon 3, Hand Weapon 3, Shield 2","Command 2, Cryptography 2, Etiquette 4, General Skills 4, Law 4, Medicine 4, Negotiation 4, Oratory 4, Research 4", "Spells"},
        {"Ranger","None","Camouflage and Pathfinder","","Hand Weapon 1 and choose one other: Archery 1, Crossbow 1, Pistol 1, or Rifle 1","Detection 1, Sneak 1, Survival 1, and Tracking 1","","","75 gc","Battle Plan: Go to Ground, Battle Plan: Reconnaissance, Battle Plan: Shadow, Camouflage, Disease Resistance, Fast Reload, Light Cavalry, Night Fighter, Pathfinder, Prowl Saddle Shot, Signal Language, Strangler, Swift Hunter, Swift Rider, Traceless Path","––","Archery 4, Crossbow 3, Hand Weapon 2, Pistol 2, Rifle 4, Thrown Weapon 4, Unarmed Combat 3","Command 3, Craft (any) 2, Cryptography 1, General Skills 4, Medicine 3, Navigation 4, Rope Use 4, Sneak 4, Survival 4, Tracking 4", ""},
        {"Rifleman","None","Crackshot, Dual Shot, and Marksman","","Rifle 1","Climbing 1, Detection 1, and Survival 1","","","50 gc, ammo bandolier, and a heavy rifle or a repeating long rifle (with powder and ammunition for ten shots)","Crackshot, Dual Shot, Fast Reload, Marksman, Night Fighter, Return Fire, Saddle Shot, Sniper, Swift Hunter, Targeteer","––","Rifle 4","Craft (gunsmithing) 4, General Skills 4, Survival 3", ""},
        {"Soldier","None","Find Cover and Sentry","","Choose two: Hand Weapon 1, Pistol 1, Crossbow 1, Great Weapon 1, Rifle 1, Thrown Weapon 1","Detection 1, Driving 1, Medicine 1, Survival 1","","","100 gc","’Jack Marshal, Cautious Advance, Cavalry Charge, Disease Resistance, Fast Reload, Find Cover, Grenadier, Hit the Deck!, Language, Ride-By Attack, Roll With It, Saddle Shot, Sentry","Connections (kingdom military or mercenary company)","Crossbow 3, Great Weapon 4, Light Artillery 3, Hand Weapon 3, Pistol 3, Rifle 4, Shield 2, Thrown Weapon 3, Unarmed Combat 3","Command 3, General Skills 4, Medicine 3, Navigation 2, Sneak 2, Survival 3", ""},
        {"Sorcerer: Fire","Gifted, Starting Career","Immunity: Fire","","Choose one: Archery 1, Crossbow 1, or Hand Weapon 1","Detection 1 and Survival 1","Fire Starter, Howling Flames, Wall of Fire","","75 gc","Camouflage, Dodger, Elemental Mastery, Immunity: Fire (Fire Sorcerer only), Traceless Path","––","Archery 3, Crossbow 3, Hand Weapon 3, Thrown Weapon 2, Unarmed Combat 2","General Skills 4, Sneak 3, Survival 3", "Spells"},
        {"Sorcerer: Ice","Gifted, Starting Career","Immunity: Cold","","Choose one: Archery 1, Crossbow 1, or Hand Weapon 1","Detection 1 and Survival 1","Blizzard, Chiller, and Ice Bolt","","75 gc","Camouflage, Dodger, Elemental Mastery, Immunity: Cold (Ice Sorcerer only), Traceless Path","––","Archery 3, Crossbow 3, Hand Weapon 3, Thrown Weapon 2, Unarmed Combat 2","General Skills 4, Sneak 3, Survival 3", "Spells"},
        {"Sorcerer: Stone","Gifted, Starting Career","","","Choose one: Archery 1, Crossbow 1, or Hand Weapon 1","Detection 1 and Survival 1","Battering Ram, Solid Ground, and Stone Stance","Storm sorcerers begin with +1 SPD and +1 to their racial maximum PHY at SPD level.","75 gc","Camouflage, Dodger, Elemental Mastery, Traceless Path","––","Archery 3, Crossbow 3, Hand Weapon 3, Thrown Weapon 2, Unarmed Combat 2","General Skills 4, Sneak 3, Survival 3", "Spells"},
        {"Sorcerer: Storm","Gifted, Starting Career","","","Choose one: Archery 1, Crossbow 1, or Hand Weapon 1","Detection 1 and Survival 1","Razor Wind, Storm Tossed, and Wind Blast","Storm sorcerers begin with +1 SPD and +1 to their racial maximum PHY at SPD level.","75 gc","Camouflage, Dodger, Elemental Mastery, Traceless Path","––","Archery 3, Crossbow 3, Hand Weapon 3, Thrown Weapon 2, Unarmed Combat 2","General Skills 4, Sneak 3, Survival 3", "Spells"},
        {"Spy","None","Battle Plan: Shadow, Cover Identity, and Language (choose one)","Connections (intelligence network)","Choose one: Hand Weapon 1, Pistol 1, or Thrown Weapon 1","Command 1, Deception 1, Detection 1, Disguise 1, and Sneak 1","","","100 gc and forged identity papers","Battle Plan: Shadow, Cover Identity, Iron Will, Language, Poison Resistance, Prowl, Signal Language, Strangler, Truth Reader, Waylay","Connections (any)","Hand Weapon 3, Pistol 3, Thrown Weapon 3, Unarmed Combat 3","Bribery 4, Command 3, Cryptography 4, Deception 4, Disguise 4, Escape Artist 4, Etiquette 4, Forgery 4, General Skills 4, Interrogation 4, Law 4, Lock Picking 2, Negotiation 4, Seduction 4, Sneak 4, Streetwise 4", ""},
        {"Stormblade","Human (Cygnaran), Starting Career, and Restricted 2nd Career","Blaster and Specialization (Storm Glaive)","Connections (Cygnaran Military)","Great Weapon 1","Command 1, Detection 1, Etiquette 1","","A character starting with the Stormblade career must choose between Aristocrat, Knight, Man-at-Arms, Military Officer, Soldier, or Warcaster for his second career.","Storm Glaive and Storm Knight armor","’Jack Marshal, Blaster, Close Shot, Load Bearing, Quick Work, Relentless Charge, Specialization (Storm Glaive)","Connections (Cygnaran military)","Great Weapon 4","Command 4, Etiquette 2, General Skills 4, Medicine 2", ""},
        {"Thief","None","Conniver and Dodger","","Hand Weapon 1 or Thrown Weapon 1","Bribery 1, Deception 1, Escape Artist 1, Lock Picking 2, Pickpocket 2, Sneak 1, and Streetwise 1","","","75 gc and thief's tools","Appraise, Camouflage, Card Sharp, Conniver, Dodger, Fleet Foot, Get Away, Language (Five Cant), Parry, Prowl,Traceless Path","Connections (criminal)","Hand Weapon 3, Pistol 2, Thrown Weapon 3, Unarmed Combat 2","Bribery 4, Craft (any) 2, Deception 4, Disguise 4, Escape Artist 4, Etiquette 1, Forgery 4, General Skills 4, Law 2, Lock Picking 4, Negotiation 4, Pickpocket 4, Sneak 4, Streetwise 4", ""},
        {"Trencher","Human, Ogrun, or Trollkin (Cygnaran), Starting Career, and Restricted 2nd Career","Bayonet Charge and Dig In","Connections (Cygnaran military)","Great Weapon 1, Rifle 1, Thrown Weapon 1","Command 1 and Detection 1","","A character starting with the Trencher career must choose between Artillerist, Military Officer, Ranger, Rifleman, Soldier, or Warcaster for his second career.","25 gc, ammo bandolier, bayonet, entrenching spade, military rifle, 3 smoke grenades, and Trencher medium infantry armor","’Jack Marshal, Anatomical Precision, Bayonet Charge, Bomber, Dig In, Fire in the Hole!, Grenadier, Hit the Deck!, Relentless Charge, Specialization (Bayonet)","Connections (Cygnaran military)","Great Weapon 3, Light Artillery 4, Hand Weapon 3, Pistol 3, Rifle 4, Thrown Weapon 4, Unarmed Combat 3","Command 3, General Skills 4, Interrogation 3, Medicine 3, Sneak 3, Survival 3", ""},
        {"Warcaster","Gifted (Focuser), Starting Career","Bond","","Hand Weapon 1 and Pistol 1","Command 1 and Detection 1","Boundless Charge and Convection","Change the character’s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they have bonded to.","Choose one of the following: suit of warcaster armor (light or medium), mechanika hand weapon, or a mechanika hand cannon (with ten rounds of ammunition). Mechanika weapons have housings of the chosen weapon, runeplates inscribed with the Bond rune, and are powered by alchemical capacitors. This item begins the game bonded to the warcaster.","Bond, Field Marshal: Magical Attack, Field Marshal: Relentless Charge, Field Marshal: Shield Guard, Natural Leader","Connections (kingdom or mercenary company)","Great Weapon 3, Hand Weapon 3, Pistol 3, Unarmed Combat 2","Command 4, General Skills 4", "Spells"},
        {"Archer","None","Adjust Aim, Blur of Motion, Dual Shot (Archery)","","Archery 1","Detection 1, Sneak 1, Survival 1","","","25 gc, bow, quiver of 10 arrows of any type","Adjust Aim, Arcing Shot, Blur of Motion, Crackshot, Dual Shot (archery), Fast Draw, Keen Eyed, Marksman, Return Fire, Saddle Shot, Shootist, Snap Fire, Targeteer","Connections (character’s tribe)","Archery 4","Craft (fletcher) 4, General Skills 4, Sneak 3, Survival 3, Tracking 3", ""},
        {"Blackclad","Human, Gifted, Member of the Circle Orboros, Starting Career","Aegis and Long-Lived","Connections (Circle Orboros)","Great Weapon 1","Lore (Orboros) 1, Negotiation 1, Survival 1","Force Bolt and Summon Vortex","","Custom battle armor, druid voulge, and the cloak and robes of a blackclad","Aegis, Artificer, Camouflage, Disease Resistance, Dominating Presence, Immunity: Cold, Immunity: Corrosion, Immunity: Electricity, Immunity: Fire, Iron Will, Language, Light Cavalry, Long-Lived, Mount Attack (Skirovik mountain goat), Natural Leader, Pathfinder, Stone Scavenger, Stonecutter, Trained Rider (Skirovik mountain goat)","Connections (any)","Great Weapon 2, Hand Weapon 2, Unarmed Combat 2","Bribery 4, Command 4, Craft (wold) 4, Cryptography 4, Deception 4, Disguise 3, General Skills 4, Interrogation 4, Investigation 4, Medicine 3, Navigation 4, Negotiation 4, Oratory 4, Research 4, Rope Use 3, Sneak 3, Survival 4", "Spells"},
        {"Bloodtracker","Female Tharn","Ambush and Specialization (Fighting Claw)","Connections (Tharn tribe)","Hand Weapon 1 and Thrown Weapon 1","Detection 1, Sneak 1, Tracking 1","","A character who chooses Bloodtracker as one of her two starting careers gains the Feat:Vendetta Mighty archetype benefit.","Bloodtracker fighting claw, 5 javelins, javelin quiver, Tharn leathers","Acrobatics, Ambush, Dodger, Fast Draw, Fleet Foot, Hunter, Knife Thrower, Pathfinder, Roll with It, Signal Language, Specialization (Fighting Claw),Traceless Path, Weapon Master (Javelin)","Connections (Circle Orboros), Connections (neighboring tribe), Connections (Tharn tribe)","Hand Weapon 4, Thrown Weapon 4, Unarmed Combat 3","Command 3, Craft (Tharn weapons and armor) 3, Cryptography 1, Escape Artist 4, General Skills 4, Navigation 3, Sneak 4, Survival 4, Tracking 4", ""},
        {"Bloodweaver","Female Tharn, Gifted, Startign Career","Blood Rites, Empower Weapon","Connections (Tharn tribe)","Hand Weapon 1","Detection 1, Lore (Devourer Wurm) 1, Sneak 1","Blood Magic: Accurate Strike, Blood Magic: Bleeder, Blood Magic: Brutal Strike","","Sacral blade and Tharn leathers","Anatomical Precision, Blood Spiller, Blood Trade, Empower Weapon, Gang, Haruspex, Inflict Pain, Shadow Magic, Two-Weapon Fighting","Connections (Circle Orboros), Connections (neighboring tribe), Connections (Tharn tribe)","Hand Weapon 4 and Unarmed Combat 3","Craft (Tharn weapons and armor) 3, General Skills 4, Medicine 3, Sneak 4, Survival 3", "Spells"},
        {"Bokor","Gatorman, Gifted","Great Power","Connections (Blindwater Congregation) or Connections (gatorman tribe)","Unarmed Combat 1","Detection 1, Intimidation 1, Lore (Kossok) 1, Lore (undead) 1","Bone Shaker and Grave Whispers","","50 gc","Death Mastery, Empower Weapon, Ghost Sight, Grave Man, Great Power, Haruspex, Possession, Soul Taker, Spirit Guide, Unhallowed","Connections (Blindwater Congregation), Connections (gatorman tribe), Connections (neighboring tribe)","Great Weapon 3 and Unarmed Combat 3","Alchemy 2, Command 3, Cryptography 3, Deception 4, General Skills 4, Interrogation 4, Medicine 2, Navigation 3, Oratory 2, Sneak 3, Survival 3", "Spells"},
        {"Bone Grinder","Gifted","Bone Grinder and Disease Resistance","","Great Weapon 1 or Hand Weapon 1","Alchemy 1, Craft (skinner) 1, Lore (extraordinary zoology) 1, Medicine 1","Arcane Bonds and Marked for Death","","25 gc, apothecary kit, skinning tools, and any one bone grinder fetish","Anatomical Precision, Bone Grinder, Brew Master, Disease Resistance, Inflict Pain, Meat Alchemy,Vivisectionist","Connections (any)","Great Weapon 3 and Hand Weapon 3","Alchemy 4, Craft (skinner) 4, General Skills 4, Investigation 2, Medicine 4, Navigation 2, Rope Use 3, Survival 3, Tracking 3", "Spells"},
        {"Brigand","None","Find Cover and Onslaught","Connections (criminal gang or character’s tribe)","Choose two: Archery 1, Crossbow 1, Great Weapon 1, Hand Weapon 1, Pistol 1, Rifle 1, Thrown Weapon 1","Detection 1, Driving 1, Intimidation 1, Sneak 1","","","75 gc","Ambush, Appraise, Backstab, Binding, Camouflage, Dodger, Fall Back, Fast Draw, Fast Reload, Find Cover, Fleet Foot, Gunfighter, Onslaught, Relentless Charge, Waylay","Connections (criminal gang or character’s tribe), Connections (human settlement)","Archery 3, Crossbow 3, Hand Weapon 4, Pistol 3, Rifle 3, Thrown Weapon 3, Unarmed Combat 3","Bribery 4, Command 2, Craft (any) 2, Deception 4, Disguise 3, Escape Artist 4, General Skills 4, Lock Picking 3, Navigation 2, Negotiation 3, Pickpocket 3, Rope Use 3, Sneak 4, Streetwise 2, Survival 2", ""},
        {"Bushwhacker","None","Crackshot and Fast Reload","","Hand Weapon 1 and Rifle 1","Climbing 1, Detection 1, Sneak 1, Survival 1","","","50 gc, ammo bandolier, and a heavy rifle or repeating rifle with powder and ammunition for 10 shots","Ambush, Crackshot, Dual Shot (Rifle), Fast Draw, Fast Reload, Go to Ground, Keen Eyed, Marksman, Night Fighter, Return Fire, Shootist, Sniper, Swift Hunter, Targeteer","––","Hand Weapon 3 and Rifle 4","Command 2, Craft (gunsmithing) 3, General Skills 4, Navigation 3, Sneak 4, Survival 3", ""},
        {"Chieftain","None","Battle Plan: Take Cover, Natural Leader, Team Leader","Connection (tribe or trollkin kriel)","Choose two: Archery 1, Great Weapon 1, Hand Weapon 1, Thrown Weapon 1, Unarmed Combat 1","Command 1, Lore (tribal) 1, Oratory 1, Survival 1","","","100 gc and a symbol of office (such as an iron crown or a wolf skin great cloak)","Battle Commander, Battle Plan: Battlefield Coordination, Battle Plan: Call to Action, Battle Plan: Coordinated Strike, Battle Plan: Take Cover, Cavalry Charge, Combat Rider, Defender, Expert Rider, Language, Natural Leader, Rallying Cry, Team Leader","Connections (any)","Archery 4, Great Weapon 4, Hand Weapon 4, Thrown Weapon 4, Unarmed Combat 4","Command 4, Deception 4, General Skills 4, Interrogation 4, Navigation 4, Negotiation 4, Oratory 4, Seduction 3, Sneak 2, Survival 3", ""},
        {"Fennblade","Trollkin","Hard, Relentless Advance, Specialization (Hooked Great Sword)","Connections (trollkin kriel)","Great Weapon 1","Command 1, Detection 1, Survival 1","","","75 gc and a hooked great sword","Cleave, Dual Fighter, Hard, Iron Will, Load Bearing, Precision Strike, Relentless Advance, Relentless Charge, Set Defense, Snag & Slash, Specialization (Hooked Great Sword)","Connections (trollkin kriel), Connections (United Kriels)","Great Weapon 4, Unarmed Combat 3","Command 3, General Skills 4, Survival 3", ""},
        {"Kriel Champion","Trollkin","Defensive Line, Iron Will, Load Bearing","Connections (trollkin kriel or United Kriels)","Great Weapon 1 and Hand Weapon 1","Command 1 and Detection 1","","","100 gc","Bodyguard, Defensive Line, Iron Will, Load Bearing, Natural Leader, Overtake, Relentless Charge, Retaliatory Strike, Rock Solid, Shield Guard, Shield Slam, Two-Weapon Fighting","Connections (trollkin kriel), Connections (United Kriels)","Great Weapon 4, Hand Weapon 4, Shield 3, Thrown Weapon 3, Unarmed Combat 4","Command 3, Craft (metalworking) 3, General Skills 4, Oratory 2, Survival 3", ""},
        {"Long Rider","Trollkin","Bull Rush, Cavalry Charge, Trained Rider (Bison)","","Great Weapon 1 and Shield 1","Animal Handling 1, Lore (Trollkin) 1, Riding 1","","","75 gc and a bison with tack","Bull Rush, Cavalry Charge, Combat Rider, Expert Rider, Follow Up, Line Breaker, Load Bearing, Mounted: Counter Charge, Ride-By Attack, Trained Rider (Bison)","Connections (trollkin kriel), Connections (United Kriels)","Great Weapon 4, Hand Weapon 3, Shield 4, Unarmed Combat 3","Command 3, General Skills 4, Survival 3", ""},
        {"Mist Speaker","Bog Trog, Gifted","Conniver","Connections (bog trog tribe or Blindwater Congregation)","Great Weapon 1 or Hand Weapon 1","Bribery 1, Deception 1, Detection 1, Sneak 1","Cloak of Fear and Phantasm","Mist Speakers begin with +1 INT and +1 to their racial maximum INT at each level.","50 gc","Advisor, Backstab, Conniver, Dodger, Sucker!","Connections (Blindwater Congregation), Connections (bog trog tribe), Connections (gatorman tribe), Connections (neighboring tribe)","Great Weapon 3, Hand Weapon 3, Unarmed Combat 3","Bribery 4, Command 3, Craft 2 (any), Deception 4, Escape Artist 3, General Skills 4, Interrogation 3, Investigation 3, Negotiation 4, Oratory 3, Seduction 2, Sneak 3, Survival 3", "Spells"},
        {"Monster Hunter","None","Big Game Hunter, Hunting Ground, Precision Strike","","Hand Weapon 1 and choose one: Archery 1, Crossbow 1, Pistol 1, or Rifle 1","Lore (extraordinary zoology) 1, Survival 1, Tracking 1","","","100 gc","Anatomical Precision, Big Game Hunter, Binding, Camouflage, Deadly Skill, Dismember, Exterminator, Hunting Ground, Pathfinder, Poison Resistance, Precision Strike, Skilled Trapper, Staredown, Survivalist","Connections (adventuring scholar)","Archery 4, Crossbow 4, Great Weapon 3, Hand Weapon 4, Pistol 3, Rifle 4, Thrown Weapon 3, Unarmed Combat 4","Craft (skinner) 4, Escape Artist 3, General Skills 4, Investigation 2, Navigation 3, Negotiation 3, Research 3, Rope Use 3, Sneak 4, Survival 4, Tracking 4", ""},
        {"Priest Of Nyssor","Nyss, Gifted, Worship of Nyssor","Empower Weapon","Connections (Fane of Nyssor)","Great Weapon 1","Craft (metalworking), Lore (Faith of Nyssor) 1, Lore (Nyss) 1, Survival 1","Hand of Fate, Hidden Path, Staying Winter’s Hand","","50 gc, Nyss claymore, Nyss leather armor","Astute, Cold Steel, Empower Weapon, Immunity: Cold, Natural Leader, Snow-Wreathed","Connections (Fane of Nyssor), Connections (human settlement), Connections (Nyss shard)","Great Weapon 3","Command 3, Craft (metalworking) 4, General Skills 4, Interrogation 3, Medicine 2, Navigation 3, Negotiation 3, Oratory 3, Research 2, Survival 3", "Spells"},
        {"Raptor","Nyss","Saddle Shot and Trained Rider (Ulk)","Connections (Nyss shard)","Archery 1 and Great Weapon 1","Animal Handling 1, Riding 1, Survival 1","","","50 gc, Nyss leather armor, and an ulk with tack and harness","Beast Handler, Cavalry Fighter, Evasive Rider, Expert Rider, Light Cavalry, Mount Attack (Ulk), Opening Salvo, Saddle Shot, Swift Rider, Trained Rider (Ulk)","Connections (Nyss shard)","Archery 3, Great Weapon 3, Unarmed Combat 2","Command 2, General Skills 4, Navigation 3, Survival 3, Tracking 4", ""},
        {"Ravager","Male Tharn","Heart Eater and Treewalker","Connections (Tharn tribe)","Choose two: Archery 1, Great Weapon 1, Hand Weapon 1 Unarmed Combat 1","Climbing 1, Detection 1, Jumping 1, Survival 1","","","Tharn leathers, and a Tharn axe or Tharn bow with a quiver of ten arrows","Consume Essence, Disease Resistance, Fearless, Heart Eater, Hyper Awareness, Overtake, Pathfinder, Specialization (Tharn Axe), Specialization (Tharn Bow), Sprint, Treewalker","Connections (Circle Orboros), Connections (neighboring tribe), Connections (Tharn tribe)","Archery 4, Great Weapon 4, Hand Weapon 4, Thrown Weapon 3, Unarmed Combat 4","Command 3, Craft (Tharn weapons and armor) 4, General Skills 4, Navigation 3, Sneak 2, Survival 4,Tracking 3", ""},
        {"Ryssovass","Nyss, Starting Career","Defender and Specialization (Nyss Great Sword)","Connections (Nyss shard)","Great Weapon 1","Command 1, Detection 1, Intimidation 1, Survival 1","","","Nyss great sword and ryssovass plate armor","Blade Shield (Nyss Great Sword), Cleave, Defender, Defensive Line, Fearless, Load Bearing, Precision Strike, Relentless Charge, Renowned, Retaliatory Strike, Set Defense, Specialization (Nyss Great Sword)","Connections (Fane of Nyssor) and Connections (Nyss shard)","Great Weapon 4 and Unarmed Combat 3","Command 4, Craft (metalworking) 4, General Skills 4, Survival 3", ""},
        {"Scout","None","Pathfinder and Survivalist","","Choose two: Archery 1, Crossbow 1, Hand Weapon 1, Pistol 1, Rifle 1, Thrown Weapon 1, Unarmed Combat 1","Detection 1, Sneak 1, Survival 1, Tracking 1","","","75 gc","Battle Plan: Reconnaissance, Battle Plan: Shadow, Camouflage, Disease Resistance, Expert Rider, Fast Reload, Knife Thrower, Light Cavalry, Night Fighter, Pathfinder, Prowl, Pursuit, Signal Language, Skilled Trapper, Survivalist, Swift Hunter, Swift Rider, Traceless Path","Connections (any)","Archery 3, Crossbow 3, Hand Weapon 3, Pistol 3, Rifle 3, Thrown Weapon 3, Unarmed Combat 3","Command 3, Craft (any) 2, Cryptography 1, General Skills 4, Investigation 3, Medicine 3, Navigation 4, Rope Use 4, Sneak 4, Survival 4, Tracking 4", ""},
        {"Shaman (Devourer Wurm)","Human or Tharn, Gifted, Worship of the Devourer Wurm","Blood Trade","Connections (Devourer cult or Tharn tribe)","Great Weapon 1 or Hand Weapon 1","Command 1, Lore (Devourer) 1, Survival 1","Bleed, Blessing of the Devourer, Cloak of the Predator","","75 gc","Aegis, Blood Trade, Disease Resistance, Flesh of Steel, Gift of the Beast, Poison Resistance, Staredown, Survivalist","Connections (Circle Orboros), Connections (Devourer cult), Connections (human tribe), Connections (Tharn tribe)","Great Weapon 3 and Hand Weapon 3","Command 3, Deception 4, Disguise 3, Escape Artist 3, General Skills 4, Interrogation 3, Medicine 2, Navigation 3, Negotiation 2, Oratory 2, Sneak 3, Survival 3", "Spells"},
        {"Shaman (Dhunia)","Farrow or Trollkin, Gifted, Worship of Dhunia","Balm of Dhunia","Connections (farrow tribe or trollkin kriel)","Great Weapon 1 or Hand Weapon 1","Animal Handling 1, Command 1, Lore (Dhunian) 1, Oratory 1","Earth’s Cradle, Inviolable Resolve, Triage","","75 gc","Balm of Dhunia, Charmer, Dispel, Fate Blessed, Natural Leader","Connections (farrow tribe), Connections (neighboring tribe), Connections (Thornfall Alliance), Connections (trollkin kriel)","Great Weapon 3 and Hand Weapon 3","Command 3, Craft (stoneworking) 4, General Skills 4, Medicine 3, Negotiation 4, Oratory 4, Survival 2", "Spells"},
        {"Slaughterhouser","Farrow, Starting Career","Fearless and Specialization (Halberd)","Connection (Thornfall Alliance)","Great Weapon 1 and Unarmed Combat 1","Command 1, Detection 1, Intimidation 1","","","25 gc, halberd, full plate armor","Broad Stroke, Cleave, Fearless, Finisher, Gang, Hack, Load Bearing, Precision Strike, Relentless Charge, Specialization (Halberd)","Connections (farrow tribe), Connections (Thornfall Alliance)","Connections (farrow tribe), Connections (Thornfall Alliance)","Command 3, General Skills 4, Survival 3", ""},
        {"Warlock: Cirlce","Human or Tharn, Gifted, Starting Career","Warlock Bond and the choice of Resonance: Devourer Warbeast or Resonance: Wold","Choose one: Connections (Circle Orboros), Connections (Tharn tribe), or Connections (Wolf of Orboros tribe)","Great Weapon 1 or Hand Weapon 1","Animal Handling 1, Command 1, Lore (Devourer Wurm or Orboros) 1","Roots of the Earth and Spirit Fang","Change the character’s arcane tradition to harnesser if he has another arcane career. A warlock can boost only with magical weapons.","25 gc and a medium-based Devourer warbeast or medium-based Wold that begins the game bonded to the warlock","Beast Handler, Calm, Earth Magic, Empower Weapon, Field Marshal: Magical Weapon, Field Marshal: Relentless Charge, Pack Hunter, Pathfinder, Resonance: Devourer Warbeast, Resonance: Wold, Stone Warder, Warlock Bond, Wold Mastery","Connections (Circle Orboros), Connections (Tharn tribe), Connections (Wolves of Orboros)","Great Weapon 3, Hand Weapon 3, Unarmed Combat 3","Command 3, General Skills 4, Sneak 3, Survival 3", "Spells"},
        {"Warlock: Farrow","Farrow, Gifted, Starting Career","Resonance: Farrow Warbeast and Warlock Bond","","Choose two: Great Weapon 1, Hand Weapon 1, Pistol 1, Rifle 1, Unarmed Combat 1","Animal Handling 1, Command 1, Survival 1","Perdition and Quagmire","Change the character’s arcane tradition to harnesser if he has another arcane career. A warlock can boost only with magical weapons.","25 gc and a medium-based Farrow warbeast or two razor boar warbeasts that begin the game bonded to the warlock","Empower Weapon, Field Marshal: Counter Charge, Field Marshal: Hog Wild, Goad, Maltreatment, Resonance: Farrow Warbeast, Souie!, Warlock Bond","Connections (farrow tribe), Connections (human settlement), Connections (Thornfall Alliance)","Great Weapon 3, Hand Weapon 3, Pistol 3, Rifle 3, Thrown Weapon 3, Unarmed Combat 3","Command 3, Deception 3, General Skills 4, Negotiation 3, Streetwise 3, Survival 3", "Spells"},
        {"Warlock: Swamp","Bog Trog or Gatorman, Gifted, Starting Career","Resonance: Swamp Warbeast and Warlock Bond","","Unarmed Combat 1 and either Great Weapon 1 or Hand Weapon 1","Animal Handling 1 and Detection 1","Carnivore and Sunder Spirit","Change the character’s arcane tradition to harnesser if he has another arcane career. A warlock can boost only with magical weapons.","25 gc and a medium-based Swamp warbeast that begins the game bonded to the warlock","Empower Weapon, Field Marshal: Counter Charge, Field Marshal: Magical Attack, Field Marshal: Poltergeist, Maltreatment, Resonance: Swamp Warbeast, Spirit Eater, Warlock Bond","Connections (Blindwater Congregation), Connections (character’s tribe), Connections (neighboring tribe)","Great Weapon 3, Hand Weapon 3, Unarmed Combat 3","Command 3, General Skills 4, Survival 3", "Spells"},
        {"Warlock: Trollkin","Trollkin, Gifted, Starting Career","Resoance: Trollblood Warbeast and Warlock Bond","Connections (trollkin kriel) or Connections (United Kriels)","Great Weapon 1 or Hand Weapon 1","Animal Handling 1, Command 1, Detection 1","Stone Strength and Stranglehold","Change the character’s arcane tradition to harnesser if he has another arcane career. A warlock can boost only with magical weapons.","25 gc and a medium-based Trollblood warbeast that begins the game bonded to the warlock","Empower Weapon, Field Marshal: Regenerate, Field Marshal: Relentless Charge, Field Marshal: Unyielding, Goad, Resonance: Trollblood Warbeast, Troll Speaker, Warlock Bond","Connections (trollkin kriel) and Connections (United Kriels)","Great Weapon 3, Hand Weapon 3, Thrown Weapon 3, Unarmed Combat 3","Command 4, General Skills 4, Survival 3", "Spells"},
        {"Warrior","None","Fast Draw and Roll with It","","Choose three: Archery 1, Crossbow 1, Great Weapon 1, Hand Weapon 1, Light Artillery 1, Rifle 1, Shield 1, Thrown Weapon 1, Unarmed Combat 1","Command 1, Detection 1, Gambling 1, Riding 1","","","100 gc","Cautious Advance, Cavalry Charge, Crossbowman, Fast Draw, Fast Reload, Find Cover, Gunner, Head-Butt, Knife Thrower, Load Bearing, Quick Work, Roll with It, Sentry, Shield Guard, Shootist, Specialization (any), Two-Weapon Fighting","––","Archery 3, Crossbow 4, Great Weapon 4, Hand Weapon 4, Light Artillery 3, Pistol 3, Rifle 3, Shield 3, Thrown Weapon 3, Unarmed Combat 4","Command 3, Craft (any) 3, General Skills 4, Interrogation 3, Medicine 3, Negotiation 3, Survival 3", ""},
        {"Wolf Of Orboros","Human, Restricted 2nd Career, Starting Career or Connections (Circle Orboros)","Dual Shot (Crossbow) and Specialization (Cleft weapon)","Connections (Wolves of Orboros)","Crossbow 1, Great Weapon 1, Hand Weapon 1","Detection 1, Survival 1, Tracking 1","","A character starting with the Wolf of Orboros career must choose Bone Grinder, Brigand, Chieftain, Monster Hunter, Scout, Devourer Shaman, Sorcerer, Circle Warlock, Warrior, or Wolf Rider for his second career.","Full plate armor, wolf pelt, and a cleft spear or a dual crossbow with a quiver of 10 bolts","Battle Plan: Brutal Charge, Bayonet Charge, Cleave, Crossbowman, Dual Shot (Crossbow), Fast Reload, Hunter, Load Bearing, Pathfinder, Precision Strike, Set Defense, Specialization (Cleft Weapon)","Connections (Circle Orboros), Connections (neighboring tribe), Connections (Tharn tribe), Connections (Wolves of Orboros)","Crossbow 4, Great Weapon 4, Hand Weapon 4","Command 3, General Skills 4, Navigation 3, Sneak 3, Survival 3, Tracking 3", ""},
        {"Wolf Rider","Human or Female Tharn, Starting Career or Connections (Circle Orboros)","Scent and Trained Rider (Duskwolk)","","Great Weapon 1 and Hand Weapon 1","Animal Handling 1, Navigation 1, Riding 1, Survival 1, Tracking 1","","","75 gc and a duskwolf with tack","Beast Handler, Expert Rider, Light Cavalry, Mount Attack (Duskwolf), Scent, Signal Howls, Swift Rider, Trained Rider (Duskwolf), Wolf Protector","Connections (Circle Orboros), Connections (neighboring tribe), Connections (Tharn tribe), Connections (Wolves of Orboros)","Great Weapon 4, Hand Weapon 4, Thrown Weapon 4, Unarmed Combat 3","General Skills 4, Survival 4, Tracking 4", ""},
        {"Ascetic","Skorne","Flesh of Steel, Long Lived, Pain Monger","","Unarmed Combat 1","Climbing 1, Detection 1, Jumping 1, Lore (philosophy of Morkaash) 1","","","10 sl worth of equipment","Acrobatics, Aegis, Blood Trade, Circular Vision, Disease Resistance, Dodger, Exalted, Excruciator, Fleet Foot, Flesh of Steel, Flying Fists, Hardened Strike, Immunity: Cold, Immunity: Fire, Iron Will, Long Lived, Overtake, Pain Monger, Poison Resistance, Rock Solid, Serpent Strike, Specialization (Katara), Transcend the Flesh, Trip, Two-Weapon Fighting, Whirlwind","––","Hand Weapon 3, Thrown Weapon 3, Unarmed Combat 4","Cryptography 4, Escape Artist 4, General Skills 4, Medicine 4, Oratory 4, Sneak 3, Survival 4", ""},
        {"Beast Handler","Skorne, Paingiver Caste","Animal Control, Beast Manipulation: Enrage","Specialization (Barbed Whip)","Hand Weapon 1","Animal Handling 1, Lore (extraordinary zoology), Lore (philosophy of Morkaash) 1, Medicine 1,Tracking 1","","A character starting with the Beast Handler career must choose Bloodrunner, Chirurgeon, Chymist, Monster Hunter, Mortitheurge, Scout, Tormentor, or Warlock: Skorne for his other career.","Barbed whip, paingiver armor, paingiver mask","Animal Control, Beast Handler, Beast Manipulation: Dominator, Beast Manipulation: Enrage, Beast Manipulation: Medicate, Big Game Hunter, Conditioning, Inflict Pain, Poison Resistance, Precision Strike, Skilled Trapper, Specialization (Barbed Whip), Specialization (Man Catcher), Staredown, Take Down","Connections (Army of the Western Reaches), Connections (paingivers), Connections (skorne house)","Great Weapon 2, Hand Weapon 3, Unarmed Combat 3","Command 2, General Skills 4, Interrogation 2, Medicine 4, Navigation 3, Rope Use 4, Sneak 3, Survival 3, Tracking 4", ""},
        {"Bloodrunner","Skorne, Paingiver Caste","Prowl, Specialization (Assassin's Blade)","Connection (paingivers)","Hand Weapon 1","Detection 1, Lore (philosophy of Morkaash) 1, Sneak 1","","A character starting with the Bloodrunner career must choose Beast Handler, Brigand, Mortitheurge, Scout, Tormentor, or Warlock: Skorne for his other career.","Assassin’s blade, paingiver armor, paingiver mask","Acrobatics, Ambush, Backstab, Battle Plan: Coordinated Strike, Blood Spiller, Deadly Skill, Fast Draw, Fleet Foot, Overtake, Precision Strike, Pursuit, Prowl, Roll With It, Shadow Magic, Signal Language, Specialization (Assassin’s Blade), Specialization (Fighting Claws), Sprint, Two-Weapon Fighting","Connections (Army of the Western Reaches), Connections (paingivers), Connections (skorne house)","Great Weapoon 2, Hand Weapon 4, Thrown Weapon 3, Unarmed Combat 4","Command 2, Cryptography 1, Disguise 4, Escape Artist 4, General Skills 4, Interrogation 2, Medicine 2, Sneak 4", ""},
        {"Cataphract","Skorne, Warrior Caste, PHY 7","Cataphract, Defensive Line, Load Bearing","Connections (skorne house)","Great Weapon 1 and Shield 1","Command 1 and Lore (hoksune code) 1","","A Cataphract must use his initial stat increases to improve his PHY stat.","Cataphract armor, shield, war spear","Broad Stroke, Cataphract, Cleave, Defensive Line, Exalted, Fast Rearm (arcus), Fearless, Hard, Iron Will, Load Bearing, Precision Strike, Relentless Charge, Retaliatory Strike, Rock Solid, Set Defense, Shield Slam, Specialization (Arcus), Specialization (Incindus), Specialization (War Spear)","Connections (Army of the Western Reaches), Connections (skorne house)","Crossbow 3, Great Weapon 4, Hand Weapon 4, Light Artillery 3, Shield 4, Unarmed Combat 4","Command 3, General Skills 4, Survival 3", ""},
        {"Chirurgeon","Skorne, Worker Caste","Pain Flow and Remedy","Connections (Corpusulem)","Hand Weapon 1","Lore (philosophy of Kexorus) 1, Lore (philosophy of Morkaash) 1, Medicine 1, Research 1","","","Chirurgeon’s toolkit, 25 sl","Anatomical Precision, Anatomist, Anesthetize, Bloodletting, Disease Resistance, Fleshcrafting, Pain Flow, Precision Strike, Remedy, Studious, Take Down","Connections (Corpusulem), Connections (skorne house)","Hand Weapon 3","Craft (any) 2, Cryptography 2, Etiquette 2, General Skills 4, Investigation 4, Medicine 4, Research 4", ""},
        {"Chymist","Skorne, Worker Caste","Distiller and Poison Resistance","","Hand Weapon 1","Chymistry 1, Lore (philosophy of Kexorus) 1, Research 1","","","Chymist’s kit, 10 sl, 10 sl of chymical items and ingredients","Conniver, Distiller, Improvised Formula, Master Chymist, Poison Resistance, Poison Glaze, Poisoner, Quick Chymist, Student of Kexorus, Studious, Thick Skin","Connections (Corpusulem), Connections (skorne house)","Hand Weapon 3,Thrown Weapon 3","Chymistry 4, Craft (any) 4, Cryptography 2, Deception 2, Etiquette 2, General Skills 4, Research 4, Sneak 2", ""},
        {"Extoller","Skorne, Gifted, Extoller Caste","Extoller","","","Detection 1, Lore (extoller) 1, Lore (philosophy of Voskune) 1, Negotiation 1, Oratory 1","Banishing Ward, Grave Whispers, Shadow Sight","","Oculus, 14 sl","Advisor, Astute, Doom Gaze, Extoller, Ghost Shield, Grave Man, Iron Will, Poltergeist, Spirit Guide","Connections (Army of the Western Reaches), Connections (skorne house)","Great Weapon 2","Command 2, Craft (stoneworking) 4, Deception 3, General Skills 4, Interrogation 3, Investigation 4, Negotiation 4, Oratory 4, Research 4", "Spells"},
        {"Ferox Rider","Skorne, Warrior Caste","Cavalry Charge, Specialization (Cavalry Spear)","Connections (skorne house)","Great Weapon 1 and Shield 1","Animal Handling 1, Lore (hoksune code) 1, Riding 1","","A character starting with the Ferox Rider career must choose Monster Hunter, Mortitheurge, Praetorian, Scout, Tyrant, Venator, Warlock: Skorne, or Warrior for his other career.","Ferox, tack, cavalry spear, shield, praetorian armor","Ambush, Cavalry Charge, Evasive Rider, Expert Rider, Maul, Mount Attack (Ferox), Mounted: Bounding Leap, Ride-By-Attack, Specialization (Cavalry Spear), Swift Rider,Trained Rider (Ferox)","Connections (Army of the Western Reaches), Connections (skorne house)","Great Weapon 4, Hand Weapon 3, Shield 3, Unarmed Combat 3","Command 3, General Skills 4, Survival 3, Tracking 3", ""},
        {"Mortitheurge","Skorne, ARC 2","Iron Will","","","Lore (philosophy of Voskune) 1 and Medicine 1","Influence, Inviolable Resolve, Stranglehold","A character who chooses Mortitheurge as one of his two starting careers gains the Feat: Revitalize Mighty archetype benefit.","25 sl","Blood Trade, Dark Dominion, Flesh of Steel, Iron Will, Life Drinker, Stay Death","Connections (Army of the Western Reaches), Connections (skorne house)","––","General Skills 4, Medicine 3, Research 3", "Spells"},
        {"Nihilator","Skorne","Berserk and Fearless","Connections (nihilator cult)","Great Weapon 1","Intimidation 1, Lore (hoksune code) 1, Lore (philosophy of Morkaash) 1","","A character who chooses Nihilator as one of his two starting careers gains the Tough Mighty archetype benefit.","Great Sword, 12 sl","Berserk, Blood Frenzy, Dual Fighter, Exalted, Excruciator, Fearless, Flesh of Steel, Relentless Advance, Silence, Sprint, Strength of Arms","Connections (Army of the Western Reaches), Connections (nihilator cult)","Great Weapon 4, Unarmed Combat 4","General Skills 4", ""},
        {"Praetorian","Skorne, Warrior Caste","First to Fight, and choose one of the following for which the character meets the requirements: Specialization (Karax Shield), Specialization (Toboresh), or Two-Weapon Fighting","Connections (skorne house)","Choose two: Great Weapon 1, Hand Weapon 1, Shield 1, Unarmed Combat 1","Command 1, Detection 1, Intimidation 1, Lore (hoksune code) 1","","A character starting with the Praetorian career must choose Cataphract, Ferox Rider, Monster Hunter, Mortitheurg, Nihilateor, Scout, Tyrant, Warlock: Skorne, or Warrior for his other career.","Praetorian plate and choose one: a toboresh, karax shield and pike, or a pair of Praetorian swords","Blade Shield (toboresh), Cleave, Combo Strike (Praetorian Sword), Defensive Line, Exalted, Fast Draw, First to Fight, Hyper Awareness, Load Bearing, Natural Leader, Precision Strike, Overtake, Roll with It, Specialization (Karax Shield), Specialization (Toboresh), Two-Weapon Fighting, Weapon Master (Praetorian Sword)","Connections (Army of the Western Reaches), Connections (skorne house)","Great Weapon 4, Hand Weapon 4, Shield 4, Unarmed Combat 4","Command 3, General Skills 4, Survival 3", ""},
        {"Tormentor","Skorne, Paingiver Caste","Take Down and Torture","Connections (paingivers)","Hand Weapon 1","Detection 1, Interrogation 1, Investigation 1, Lore (philosophy of Morkaash) 1, Medicine 1","","A character starting with the Tormentor career must choose Beast Handler, Bloodrunner, Chirurgeon, Chymist, Mortitheurge, or Warlock: Skorne for his other career.","Paingiver armor, Paingiver mask, 11 sl","Advisor, Astute, Binding, Dominating Presence, Inflict Pain, Iron Will, Language (any), Specialization (Fighting Claws), Specialization (Man Catcher), Take Down, Torture, Truth Reader, Two-Weapon Fighting, Waylay","Connections (Army of the Western Reaches), Connections (paingivers), Connections (skorne house)","Great Weapon 3, Hand Weapon 3","Command 2, Cryptography 4, Deception 4, Interrogation 4, Investigation 4, Medicine 4, Negotiation 4, Rope Use 4, Sneak 3", ""},
        {"Tyrant","Skorne, Warrior Caste","Battle Plan: Call to Action and Natural Leader","Connections (skorne house)","Great Weapon 1 and Hand Weapon 1","Command 1, Intimidation 1, Lore (hoksune code) 1, Lore (household)","","A character starting with the Tyrant career must choose Cataphract, Ferox Rider, Monster Hunter, Mortitheurge, Praetorian, Scout, Warlock: Skorne, or Warrior for his other career.","100 sl","Battle Commander, Battle Plan: Call to Action, Battle Plan: Press Forward, Battle Plan: Relentless Charge, Cavalry Charge, Conniver, Dodger, Dominating Presence, Exalted, Hyper Awareness, Iron Will, Load Bearing, Natural Leader, Poison Resistance, Rallying Cry, Roll with It, Trained Rider (Ferox)","Connections (any)","Great Weapon 4, Hand Weapon 4, Unarmed Combat 3","Bribery 4, Command 4, Cryptography 3, Deception 3, General Skills 4, Interrogation 3, Investigation 2, Negotiation 4, Oratory 4", ""},
        {"Venator","Skorne, Warrior Caste","Fast Reload, Sentry, Specialization (Reiver)","","Hand Weapon 1, Reiver 1, Thrown Weapon 1","Detection 1 and Survival 1","","","Skorne infantry armor, reiver, 4 ammo cones, 2 gas canisters, reiver ammo bandolier, 12 sl","Covering Fire, Crackshot, Fast Reload, Fall Back, Find Cover, High-Pressure Fire, Hit the Deck!, Return Fire, Roll with It, Saddle Shot, Sentry, Street Sweeper, Specialization (Reiver), Specialization (Sling), Swift Hunter","Connections (Army of the Western Reaches), Connections (skorne house)","Hand Weapon 3, Light Artillery 3, Reiver 4, Thrown Weapon 4","Command 3, General Skills 4, Survival 3", ""},
        {"Warlock: Skorne","Skorne","Resonance: Skorne Warbeast and Warlock Bond","","Great Weapon 1 or Hand Weapon 1","Command 1, Detection 1, Lore (philosophy of Morkaash) 1","Medicate and Muzzle","A character who selects this career after character creation must have either the Gifted archetype or the Mortitheurge career. Change the character’s arcane tradition to harnesser if he has another arcane career. A warlock can only boost with magical weapons.","A medium-based Skorne warbeast that begins the game bonded to the warlock, 12 sl","Blood Trade, Empower Weapon, Field Marshal: Relentless Charge, Maltreatment, Resonance: Skorne Warbeast, Spirit Eater, Vampiric Harvest, Warlock Bond","Connections (Army of the Western Reaches), Connections (skorne house)","Great Weapon 3, Hand Weapon 3","Animal Handling 2, Command 3, General Skills 4", ""},
        {"Arcane Tempest Gun Mage","Human (Cygnaran), Gifted","Craft Rune Shot, Runesmith, Fast Reload","Connections (Cygnaran military)","Pistol 1 or Rifle 1","Detection 1 and Intimidation 1","Rune Shot: Accuracy, Rune Shot: Brutal, Rune Shot: Thunderbolt","A character cannot have both the Arcane Tempest Gun Mage and the standard Gun Mage careers. A character starting the game as a member of the Arcane Tempest must choose Aristocrat, Horseman, Military Officer, Pistoleer, Ranger, Rifleman, Soldier, Spy, or Warcaster for his second career.","25 gc, armored great coat, ammo bandolier, magelock pistol or rifle (with powder and ten rounds of ammunition), and a rune shot casting kit","Arcane Precision, Craft Rune Shot, Fast Draw, Fast Reload, Gunfighter, Keen Eyed","Connections (gun mage order)","Pistol 4, Rifle 4","General Skills 4, Seduction 2", "Spell"},
        {"Warcaster: Cygnaran","Human (Cygnaran), Gifted (Focuser), Starting Career","Bond","Connections (Cygnaran military)","Hand Weapon 1 and Pistol 1","Command 1 and Detection 1","Arcane Bolt and Blur","A character cannot be a Cygnaran Warcaster and a standard Warcaster. A character starting the game as Cygnaran Warcaster must choose Arcane Mechanik, Arcanist, Aristocrat, Field Mechanik, Gun Mage, Horseman, Knight, Man-At-Arms, Military Officer, Pistoleer, Ranger, Rifleman, Soldier, Sorcerer, Stormblade, or, Trencher for his second career. Change the character’s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they have bonded to.","Choose one of the following: suit of warcaster armor (light or medium), mechanika hand weapon, or a mechanika hand cannon (with ten rounds of ammunition). Mechanika weapons have housings of the chosen weapon, runeplates inscribed with the Bond rune, and are powered by alchemical capacitors. This item begins the game bonded to the warcaster.","Bond, Field Marshal: Magical Attack, Field Marshal: Relentless Charge, Field Marshal: Shield Guard, Natural Leader","Connections (kingdom or mercenary company)","Great Weapon 3, Hand Weapon 3, Pistol 3, Unarmed Combat 2","Command 4, General Skills 4", "Spells"},
        {"Illuminated Arcanist","Gifted, Worship of Morrow","Great Power","Connections (Order of Illumination)","","Lore (Arcane) 1 and Research 1","Eyes of Truth, Guided Blade, and Occultation","A character who chooses Arcanist as one of his two starting careers gains the Rune Reader Gifted archetype benefit. A character cannot be an Illuminated Arcanist and a standard Arcanist.","75 gc","Arcane Defenses, Arcane Scholar, Great Power, University Education","Connections (Magical Order)","––","Craft 2 (any), Etiquette 2, General Skills 4, Negotiation 2, Oratory 2, Research 4", "Spells"},
        {"Stormsmith","Human (Cygnaran)","Specialization (Stormcaller and Lightning Rod), Weatherman, Weather Vane","Connections (Cygnaran military)","Great Weapon 1","Mechanikal Engineering 1 and Stormsmithing 1","","","Stormsmith armor, stormcaller and lightning rod","Electromancer, Eye of the Storm, Hit the Deck!, Maestro, Specialization (Stormcaller and Lightning Rod), Storm Booster, Weatherman, Weather Vane","Connections (Cygnaran military)","Great Weapon 2, Hand Weapon 2","General Skills 4, Mechanikal Engineering 3, Stormsmithing 4", ""},
        {"Greylord","Human (Khadoran), Gifted","Great Power","Connections (Greylords covenant)","","Lore (Arcane) 1 and Research 1","Blizzard, Frostbite, and Protection from Cold","A character cannot have both the Greylord and standard Arcanist careers. A character starting the game as a member of the Greylords must choose Alchemist, Arcane Mechanik, Aristocrat, Explorer, Horseman, Investigator, Military Officer, Sorcerer, Spy, or Warcaster for his second career. A character who chooses Arcanist as one of his two starting careers gains the Rune Reader Gifted archetype benefit.","75 gc","Arcane Defenses, Arcane Scholar, Great Power, University Education","Connections (Magical Order)","––","Craft 2 (any), Etiquette 2, General Skills 4, Negotiation 2, Oratory 2, Research 4", "Spells"},
        {"Warcaster: Khadoran","Human (Khadoran), Gifted (Focuser), Starting Career","Bond","Connections (Khadoran military)","Hand Weapon 1 and Pistol 1","Command 1 and Detection 1","Boundless Charge, Jump Start, and Razor Wind","A character cannot be a Khadoran Warcaster and a standard Warcaster. A character starting the game as a Khadoran Warcaster must choose Arcane Mechanik, Arcanist, Aristocrat, Assault Kommando, Horseman, Investigator, Iron Fang, Military Officer, Pistoleer, Ranger, Rifleman, Soldier, Sorcerer, or Spy for his second career. second career. Change the character’s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they have bonded to.","Choose one of the following: suit of warcaster armor (light or medium), mechanika hand weapon, or a mechanika hand cannon (with ten rounds of ammunition). Mechanika weapons have housings of the chosen weapon, runeplates inscribed with the Bond rune, and are powered by alchemical capacitors. This item begins the game bonded to the warcaster.","Bond, Field Marshal: Magical Attack, Field Marshal: Relentless Charge, Field Marshal: Shield Guard, Natural Leader","Connections (kingdom or mercenary company)","Great Weapon 3, Hand Weapon 3, Pistol 3, Unarmed Combat 2","Command 4, General Skills 4", "Spells"},
        {"Assault Kommando","Human (Khadoran)","Defensive Line and Onslaught","Connections (Khadoran Military)","Hand Weapon 1, Rifle 1, and Shield 1","Command 1 and Detection 1","","A character starting with the Assault Kommando career must choose Military Officer, Ranger, Rifleman, Soldier, or Warcaster for his other career.","Assault kommando armor, Vislovski carbine (with powder and ten rounds of ammunition), combat shield, and three strangle gas grenade launcher rounds","Battle Plan: Reconnaissance, Defensive Line, Gunfighter, Load Bearing, Onslaught, Quick Work, Relentless Charge, Signal Language, Two-Weapon Fighting","Connections (Khadoran military)","Hand Weapon 3, Light Artillery 3, Rifle 4, Shield 3, Unarmed Combat 3","Command 3, Cryptography 2, General Skills 4, Interrogation 3, Medicine 3, Survival 3", ""},
        {"Doom Reaver","Human (Khadoran), Mighty, Starting Career","Abomination, Berserk, Bloodlust, Fearless","","Great Weapon 1","Detection 1, Intimidation 1","","A character starting with the Doom Reaver career must choose Cutthroat, Horseman, Pirate, Ranger, Soldier, or Thief for his other career.","Fellblade","Abomination, Berserk, Bloodlust, Fearless, Fearsome Howl, Iron Will, Language (Orgoth), Precision Strike, Relentless Charge, Silence","––","Great Weapon 4, Unarmed Combat 3","General Skills 4, Survival 3, Tracking 3", ""},
        {"Horseman","None","Cavalry Charge and Combat Rider","","Choose three of the following: Great Weapon 1, Hand Weapon 1, Lance 1, or Pistol 1","Riding 1","","A character starting with the Iron Fang career can choose Horseman for his other career. Since horses are uncomfortable in the presence of trollkin, trollkin characters cannot take this career.","25 gc, warhorse with tack and heavy barding","Cavalry Charge, Combat Rider, Expert Rider, Mounted: Counter Charge, Ride-By Attack, Saddle Shot, Swift Rider, Trained Rider (Any)","––","Great Weapon 4, Hand Weapon 2, Lance 4, Pistol 2, Unarmed Combat 2","Command 3, General Skills 4, Navigation 3", ""},
        {"Man-O-War","Human (Khadoran)","Ironhead and Load Bearing","Connections (Khadoran military)","Great Weapon 1, Light Artillery 1, and Shield 1","Command 1 and Mechanikal Engineering 1","","A character starting with the Man-O-War career must choose Aristocrat, Field Mechanik, Horseman. Man-at-Arms, Military Officer, or Soldier for his other career.","Man-O-War armor and one of the following options:" +
                "\n\n\t• Annihilator blade and Man-O-War shield cannon (with powder and ammunition for ten shots)" +
                "\n\t• Bombardier grenade cannon, Man-O-War ammo bandolier, four cannon grenades\n" +
                "\n\t• Ice maul","Cleave, Defensive Line, Girded, Head-Butt, Ironhead, Load Bearing, Man of Iron, Patch Up, Rock Steady, Shield Slam, Steady, Steam Jockey","Connections (Khadoran military)","Great Weapon 4, Light Artillery 4, Shield 3, Unarmed Combat 3","Command 3, General Skills 4, Mechanikal Engineering 2", ""},
        {"Llaelese Warcaster","Human (Llaelese), Gifted (Focuser), Starting Career","Bond","","Hand Weapon 1 and Pistol 1","Command 1 and Detection 1","Blur and Twister","A character cannot be a Llaelese warcaster and a standard warcaster. A character starting the game as a Llaelese Warcaster must choose Aristocrat, Duelist, Field Mechanik, Gun Mage, Highwayman, Horseman, Military Officer, Pistoleer, Sorcerer, or Spy for his second career. Change the character’s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they have bonded to.","Choose one of the following: suit of warcaster armor (light or medium), mechanika hand weapon, or a mechanika hand cannon (with ten rounds of ammunition). Mechanika weapons have housings of the chosen weapon, runeplates inscribed with the Bond rune, and are powered by alchemical capacitors. This item begins the game bonded to the warcaster.","Bond, Field Marshal: Magical Attack, Field Marshal: Relentless Charge, Field Marshal: Shield Guard, Natural Leader","Connections (kingdom or mercenary company)","Great Weapon 3, Hand Weapon 3, Pistol 3, Unarmed Combat 2","Command 4, General Skills 4", "Spells"},
        {"Amethyst Rose Gun Mage","Human (Llaelese), Gifted","Craft Rune Shot, Runesmith, Fast Reload","Connections (Loyal Order of the Amethyst Rose)","Pistol 1 or Rifle 1","Detection 1 and Intimidation 1","Rune Shot: Accuracy, Rune Shot: Brutal, Occultation","A character cannot have both the Amethyst Rose Gun Mage and the standard Gun Mage careers. A Gun Mage character starting the game as a member of the Amethyst Rose must choose Duelist, Highwayman, Horseman, Military Officer, Pistoleer, Spy, or Warcaster for his second career.","25 gc, ammo bandolier, magelock pistol or rifle (with powder and ten rounds of ammunition), and a rune shot casting kit","Arcane Precision, Craft Rune Shot, Fast Draw, Fast Reload, Gunfighter, Keen Eyed","Connections (gun mage order)","Pistol 4, Rifle 4","General Skills 4, Seduction 2", "Spell"},
        {"Maritime Order of the Trident Arcanist","Human (Ordic), Gifted","Great Power","Connections (Ordic military)","Hand Weapon 1 and Pistol 1","","Deadeye, Extinguisher, and Triage","A character cannot have both the Maritime Order of the Trident Arcanist and standard Arcanist careers. A character starting the game as a Maritime Order of the Trident Arcanist must choose Arcane Mechanik, Aristocrat, Explorer, Marine (Soldier), Military Officer, Ordic Warcaster (Warcaster), Pirate, Priest (Morrow), or Sorcerer for his second career. A character who chooses Arcanist as one of his two starting careers gains the Rune Reader Gifted archetype benefit.","75 gc","Arcane Defenses, Arcane Scholar, Great Power, University Education","Connections (Magical Order)","Hand Weapon 3, Pistol 3","Craft 2 (any), Etiquette 2, General Skills 4, Negotiation 2, Oratory 2, Research 4", "Spells"},
        {"Warcaster: Ordic","Human (Ordic), Gifted (Focuser), Starting Career","Bond","Connections (Ordic military)","Hand Weapon 1 and Pistol 1","Command 1 and Detection 1","Convection and Fortune","A character cannot be an Ordic Warcaster and a standard Warcaster. A character starting the game as an Ordic Warcaster must choose Arcane Mechanik, Arcanist, Aristocrat, Artillerist, Duelist, Explorer, Field Mechanik, Horseman, Man-at-Arms, Military Officer, Pirate, Priest (Morrowan), Soldier, or Sorcerer for his second career. Change the character’s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they have bonded to.","Choose one of the following: suit of naval warcaster armor, mechanika hand weapon, or a mechanika hand cannon (with ten rounds of ammunition). Mechanika weapons have housings of the chosen weapon, runeplates inscribed with the Bond rune, and are powered by alchemical capacitors. This item begins the game bonded to the warcaster.","Bond, Field Marshal: Magical Attack, Field Marshal: Relentless Charge, Field Marshal: Shield Guard, Natural Leader","Connections (kingdom or mercenary company)","Great Weapon 3, Hand Weapon 3, Pistol 3, Unarmed Combat 2","Command 4, General Skills 4", "Spells"},
        {"Artillerist","None","Battle Plan: Close Fire and Scorched Earth","","Heavy Artillery 1, Light Artillery 1, Pistol 1, Rifle 1","Command 1, Detection 1, Driving 1","","","75 gc, deck gun (with powder and ten rounds of ammunition)","Advisor, Battle Plan: Close Fire, Battle Plan: Orchestrate Fire, Bomber, Double Powder Ration, Grenadier, Hit the Deck!, Scorched Earth, Test the Wind","Connections (kingdom military or mercenary company)","Hand Weapon 3, Heavy Artillery 4, Light Artillery 4, Pistol 3, Rifle 3, Thrown Weapon 3","Craft (ordnance) 4, Command 3, General Skills 4, Rope Use 4, Survival 3", ""},
        {"Vassal Of Menoth","Human (Menite), Gifted, Starting Career","Inscribe Formulae","Connections (Vassals of Menoth)","Hand Weapon 1 or Rifle 1","Craft (gunsmithing) 1, Craft (metalworking) 1, and Mechanikal Engineering 1","Arcane Bolt, Ashen Veil, and Short Out","A character starting the game as a Vassal of Menoth must choose Alchemist, Arcanist, Field Mechanik, Priest (Menite), or Sorcerer for his second career. A character cannot have both the Vassal of Menoth and standard Arcane Mechanik careers.","50 gc, Vassal Armor, and a rune etching kit. A Vassal of Menoth/Field Mechanik character can start with a Protectorate light warjack with a stock cortex and up to 200 gc in weapons instead of a light laborjack.","'Jack Marshal, Ace Commander, Arcane Engineer, Drive: Assault, Drive: Pronto, Inscribe Formulae, Resourceful, Steamo","Connections (Mechaniks organization)","Hand Weapon 2, Light Artillery 2, Rifle 2","Command 1, Craft 4 (any), Cryptography 3, General Skills 4, Mechanikal Engineering 4, Negotiation 2, Research 3.","Spells"},
        {"Crucible Guard","Human (Cygnaran, Llaelese, or Ordic)","Find Cover and Sentry","Connections (Golden Crucible)","Rifle 1 and Thrown Weapon 1","Detection 1, Driving 1, Medicine 1, Survival 1","","A character cannot have both the Crucible Guard and the standard Soldier career. A character starting the game as a Crucible Guard must choose Artillerist, Field Mechanik, Horseman, Investigator, Man-at-Arms, Military Officer, Rifleman, Or Warcaster for his second career.","Crucible armor, 250 gc worth of grenades and Crucible Arms weapons and ammunition","’Jack Marshal, Cautious Advance, Cavalry Charge, Disease Resistance, Fast Reload, Find Cover, Grenadier, Hit the Deck!, Language, Ride-By Attack, Roll With It, Saddle Shot, Sentry","Connections (kingdom military or mercenary company)","Crossbow 3, Great Weapon 4, Light Artillery 3, Hand Weapon 3, Pistol 3, Rifle 4, Shield 2, Thrown Weapon 3, Unarmed Combat 3","Command 3, General Skills 4, Medicine 3, Navigation 2, Sneak 2, Survival 3", ""},
        {"Marine","None","Boarding Action and either Specialization (Cutlass) or Specialization (Gaff Spear)","","Choose two: Hand Weapon 1, Pistol 1, Crossbow 1, Great Weapon 1, Rifle 1, Thrown Weapon 1","Detection 1, Medicine 1, Jumping 1, Sailing 1, Swimming 1","","A character cannot have both the Marine and standard Soldier careers.","100 gc","’Jack Marshal, Cautious Advance, Cavalry Charge, Disease Resistance, Fast Reload, Find Cover, Grenadier, Hit the Deck!, Language, Ride-By Attack, Roll With It, Saddle Shot, Sentry, Specialization (Cutlass), Specialization (Gaff Spear)","Connections (kingdom military or mercenary company)","Crossbow 3, Great Weapon 4, Light Artillery 3, Hand Weapon 3, Pistol 3, Rifle 4, Shield 2, Thrown Weapon 3, Unarmed Combat 3","Command 3, General Skills 4, Medicine 3, Navigation 2, Sailing 3, Sneak 2, Survival 3", ""},
        {"Warcaster: Protectorate","Human (Menite), Gifted (Focuser), Starting Career","Bond","Connections (Protectorate military)","Hand Weapon 1 and Pistol 1","Command 1 and Detection 1","Ashen Veil and Immolation","A character cannot be a Protectorate Warcaster and a standard Warcaster. A character starting the game as a Protectorate Warcaster must choose Allegiant of the Order of the Fist, Cutthroat, Duelist, Exemplar, Field Mechanik, Paladin of the Order of the Wall, Priest, Reclaimer, or Scrutator for his second career. A character cannot have both the Protectorate Warcaster and standard Warcaster careers. Change the character’s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they have bonded to.","Choose one of the following: suit of warcaster armor (light or medium), mechanika hand weapon, or a mechanika hand cannon (with ten rounds of ammunition). Mechanika weapons have housings of the chosen weapon, runeplates inscribed with the Bond rune, and are powered by alchemical capacitors. This item begins the game bonded to the warcaster.","Bond, Field Marshal: Magical Attack, Field Marshal: Relentless Charge, Field Marshal: Shield Guard, Natural Leader","Connections (kingdom or mercenary company)","Great Weapon 3, Hand Weapon 3, Pistol 3, Unarmed Combat 2","Command 4, General Skills 4", "Spells"},
        {"Allegiant","Human (Menite), Starting Career","Flesh of Steel, Hardened Strike, Shifting Sands Stance","Connections (Order o the Fist)","Unarmed Combat 1","Detection 1, Jump 1, Sneak 1","","A character starting with the Allegiant of the Order of the Fist career must choose Cutthroat, Investigator, Priest (Menoth), Ranger, Scrutator, Spy, or Warcaster for his other career.","","Acrobatics, Chain Attack: Body Slam, Circular Vision, Fist of God, Fleet Foot, Flesh of Steel, Flying Fists, Hardened Strike, Iron Will, Precision Strike, Reed in the Wind, Serpent Strike, Shifting Sands Stance, Steady, Trip, Waylay, Whirlwind","Connections (Order of the Fist)","Hand Weapon 3, Unarmed Combat 4","General Skills 4, Interrogation 3, Law 3, Sneak 4, Survival 4", ""},
        {"Exemplar","Human (Menite), Starting Career","Aegis","Connections (Exemplar Order)","Great Weapon 1 and Hand Weapon 1","Command 1 and Lore (Menite faith)","","A character starting with the Exemplar career must choose Horseman, Man-at-Arms, Military Officer, Ranger, Soldier, or Warcaster for his other career. A character who chooses Exemplar as one of his two starting careers gains the Righteous Anger Mighty archetype benefit.","Exemplar plate and one weapon: blazing sword, consecrated halberd, or relic blade","Aegis, Chain Attack: Smite, Divine Fortitude, Imperishable Conviction, Iron Will, Load Bearing, Precision Strike, Relentless Advance, Restoration, Sanguine Bond, Two-Weapon Fighting","Connections (Exemplar Order)","Crossbow 3, Great Weapon 4, Hand Weapon 4, Lance 4, Shield 3, Unarmed Combat 3","Command 4, General Skills 4, Medicine 2, Navigation 2, Survival 2", ""},
        {"Paladin","Human (Menite), Starting Career","Specialization (Firebrand) and Stone-and-Mortar Stance","Connections (Order of the Wall)","Great Weapon 1 and Shield 1","Command 1, Etiquette 1, and Lore (Menite faith) 1","","A character starting with the Paladin of the Order of the Wall career must choose Aristocrat, Horseman, Investigator, Man-at-Arms, Military Officer, Priest (Menite), Ranger, Soldier, or Warcaster for his other career.","Firebrand, full plate, and shield","Fearless, Iron Will, Load Bearing, Impervious Wall Stance, Natural Leader, Precision Strike, Retaliatory Strike, Specialization (Firebrand), Stone-and-Mortar Stance (p. 362)","Connections (Order of the Wall)","Great Weapon 4, Hand Weapon 4, Shield 4, Unarmed Combat 3","Command 4, Etiquette 2, General Skills 4", ""},
        {"Reclaimer","Human (Menite), Starting Career","Oath of Silence, Reclaim, Signal Language, Whispers of the Creator","Connections (Reclaimant Order)","Great Weapon 1","Cryptography 1, Lore (Menite faith) 1, and Lore (Urcaen) 1","","A character starting with the Reclaimer career must choose Arcanist, Field Mechanik, Investigator, Priest (Menite), Soldier, or Warcaster for his other career.","Reclaimant’s mask, ten grave markers, and a Reclaimant torch","Communion, Fearless, Gatekeeper, Immunity: Fire, Oath of Silence, Reclaim, Signal Language, Soulstorm, Urcaen's Gate, Whispers of the Creator","Connections (Reclaimant Order)","Great Weapon 3, Hand Weapon 3","Cryptography 3, General Skills 4", ""},
        {"Scrutator","Human (Menite), Gifted, Starting Career","Authority, Torture","Connections (Temple of Menoth)","Great Weapon 1 and Hand Weapon 1","Detection 1, Interrogation 1, Intimidation 1, Law 1, and Lore (Menite Faith) 1","Chasten and Influence","A character starting with the Scrutator career must choose Allegiant of the Order of the Fist, Investigator, Military Officer, Priest (Menite), or Warcaster for his other career.","100 gc, Scrutator’s masked helm, and a wrack","Authority, Battle Plan: Call to Action, Dominating Presence, Iron Will, Language, Natural Leader, Rallying Cry, Torture","Connections (Temple of Menoth)","Great Weapon 3, Hand Weapon 3","Command 4, General Skills 4, Interrogation 4, Law 4, Medicine 2, Negotiation 4, Oratory 4", "Spells"},
        {"Guttersnipe","Gobber","Lost in the Crowd, Low Breeding, and Perfect Timing","Black Market","Choose one: Hand Weapon 1, Pistol 1, Sling 1, Thrown 1, or Unarmed Combat 1","Deception 1, Escape Artist 1, Sneak 1, and Streetwise 1","","","50 gc","Astute, Camouflage, Disease Resistance, Dodger, Find Cover, Flash Thief, Hit ’Em Low, Language, Lost in the Crowd, Low Breeding, Perfect Timing, Roll With It, Scoping it Out","Black Market","Hand Weapon 3, Pistol 3, Sling 3, Thrown 3, or Unarmed Combat 3","Bribery 4, Deception 4, Disguise 4, Escape Artist 4, General Skills 4, Negotiation 4, Pickpocket 4, Sneak 4, Streetwise 4", ""},
        {"Labor Korune","Ogrun","Iron Will and Low Breeding","Workers Union (Ogrun)","Unarmed Combat 1","Command 1, Craft 1 (choose from Metalworking, Stoneworking, or Carpentry), Negotiation 1, and Streetwise 1","","","75 gc","’Jack Marshal, Battle Plan: Call to Action, Brawler, Drive: Pronto, Gang, Heave Ho, Iron Will, Language, Low Breeding, Natural Leader, Rallying Cry","Workers Union","Unarmed Combat 4, Pistol 2","Bribery 3, Command 4, Craft 4 (chosen at career selection), Deception 2, Etiquette 2, General Skills 4, Mechanikal Engineering 2, Medicine 2, Negotiation 4, Streetwise 4", ""},
        {"Pugilist","Ogrun or Trollkin","Brawler and Hulking Presence","","Hand Weapon 1 and Unarmed Combat 1","Detection 1, Intimidation 1, Streetwise 1","","A character who chooses Pugilist as one of his two starting careers gains +1 PHY or +1 STR. This adjustment can increase a character’s PHY and STR above his racial maximums.","100 gc","Brawler, Defender, Flying Fists, Grappler, Head-Butt, Heave-Ho, Hulking Presence, Rock Solid, Trip, Waylay","––","Hand Weapon 3, Unarmed Combat 4","Bribery 3, Etiquette 3, General Skills 4, Interrogation 2, Intimidation 4, Law 2, Negotiation 3, Seduction 2, Streetwise 4", ""},
        {"Searforge Trader","Dwarf","Appraise and Counter Offer","Searforge Commission","Hand Weapon 1 or Pistol 1","Bribery 1, Law 1, and Negotiation 1","","A character who chooses Searforge Trader as one of his two starting careers gains 50 gc each month from his business investments.","150 gc","Always a Deal to be Made, Appraise, Conniver, Counter Offer, Language, Port of Call, Silver Tongued","Searforge Commission","Hand Weapon 3, Pistol 3","Bribery 4, Command 2, Deception 4, Etiquette 4, General Skills 4, Law 4, Navigation 4, Negotiation 4, Oratory 3, Survival 2", ""},
        {"Seeker","Iosan","Cover Identity, Language, Team Player, and University Education","Seekers","Hand Weapon 1 or Pistol 1","Deception 1, Disguise 1, Etiquette 1, Negotiation 1, Lore (any) 1, and Research 1","","","100 gc","Advisor, Cover Identity, Instructor, Iron Will, Language, Power of Truth, Team Leader, Team Player, University Education","Seekers","Hand Weapon 2, Pistol 2","Bribery 3, Cryptography 4, Deception 4, Disguise 2, Etiquette 4, General Skills 4, Medicine 2, Navigation 4, Negotiation 4, Oratory 4, Research 4, Streetwise 2, Survival 2", ""},
        {"Urban Nomad","Nyss","Adaptable [Urban]","","Archery 1 and Great Weapon 1","Climbing 1, Jumping 1, Sneak 1, and Survival 1","","A character who chooses Urban Nomad as one of his two starting careers gains the Preternatural Awareness Skilled archetype benefit.","Nyss Claymore and Nyss Bow","Adaptable [Urban], Archer, Crackshot, Fast Reload, Keen Eyed, Marksman, Night Fighter, Roll With It, Signal Language, Street Survivor, Swift Hunter,Targeteer","––","Archery 4, Great Weapon 4, Hand Weapon 3, Unarmed Combat 3","Bribery 2, Escape Artist 4, General Skills 4, Navigation 2, Sneak 4, Survival 4", ""},
        {"Thamarite Advocate","Human (Thamarite), Gifted","Corruptor, Imbue Weapon, Language (Telgesh)","","Hand Weapon 1 or Pistol 1","Lore (Thamarite) 1 and choose two of the following: Deception 1, Etiquette 1, Lore (any subject) 1, Research 1, Seduction 1, or Thrall Crafting 1","Bleed and Ashen Cloud","A starting Thamarite Advocate cannot take Warlock as his second career. Abilities: Corruptor, Imbue Weapon, and Language (Telgesh)","100 gc","Black Tongue, Corruptor, Dark Scribe, Ghost Shield, Grave Man, Haruspex, Imbue Weapon, Inscribe Thrall Rune, Iron Will, Language, Necromancer, Shadow Magic, Soul Taker, Soul Thief","Connections (Thamarite Sept)","Hand Weapon 3, Pistol 3","Bribery 4, Cryptography 4, Deception 4, Disguise 3, Etiquette 3, General Skills 4, Interrogation 2, Law 4, Medicine 2, Negotiation 4, Oratory 4, Research 4, Seduction 4, Sneak 3, Streetwise 3, Thrall Crafting 4", "Spells"},
        {"Priest Of Cyriss","Human, Gifted, Worshipper of Cyriss","Enigma Cipher","Connections (Convergence of Cyriss)","Hand Weapon 1","Lore (Cyriss) 1, Mechanikal Engineering 1","Guided Blade and Dissolution Bolt","A character who chooses Priest of cyriss as one of his two starting careers gains the Genius Intellectual archetype benefit.","Optifex armor and a tuning kit","Blaster, Bodge, Choir, Clockwork Transcendence, Enigma Cipher, Inscribe Formulae, Language, Vessel Upgrade","Connections (Convergence of Cyriss)","––","Alchemy 3, Command 3, Craft (any) 4, Cryptography 4, General Skills 4, Mechanikal Engineering 4, Research 4", "Spells"},
        {"Warcaster: Cyriss","Human, Gifted, Worshipper of Cyriss, Starting Career","Bond, Convergence Warcaster","Connections (Convergence of Cyriss)","Great Weapon 1 and Hand Weapon 1","Detection 1 and Mechanikal Engineering 1","Arcane Strike, Jump Start, and Temper Metal","A character starting with the Cyriss Warcaster career must choose between Alchemist, Arcane Mechanik, Arcanist, Aristocrat, Explorer, Field Mechanik, Gun Mage, Investigator, Man-At-Arms, Military Officer, or Priest of Cyriss for his other career. Change the character's arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons to which he has bonded.","Choose one of the following: suit of warcaster armor (light or medium), mechanika hand weapon, or a light vector. Mechanika weapons have housings of the chosen weapon type, runeplates inscribed with the Bond rune, and are powered by clockwork capacitors. This item begins the game bonded to the warcaster.","Blaster, Bond, Clockwork Transcendence, Convergence Warcaster, Field Marshal: Celestial Harmony, Field Marshal: Magical Attack, Field Marshal: Shield Guard, Overpower, Vessel Upgrade","––","Great Weapon 3, Hand Weapon 3","Command 3, Craft (any) 3, General Skills 4, Mechanikal Engineering 3, Research 3", "Spells"},
        {"Ironhead","Dwarf or Human","Ironhead and Tinkerer","Connections (mechaniks association)","Great Weapon 1 or Light Artillery 1","Craft (metalworking) 1 and Mechanikal Engineering 1","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
        {"Warlock: Legion","Nyss, Chosen by Everblight","Athanc Shard, Resonance: Everblight Warbeast, and Warlock Bond","","Archery 1, Great Weapon 1, or Hand Weapon 1","Command 1, Detection 1, Lore (dragons) 1","Draconic Blessing and Razor Wind","Change the character’s arcane tradition to harnesser if she has another arcane career. A warlock can only boost with magical weapons.","25 gc and a medium-based Everblight warbeast or two lesser warbeasts that begin the game bonded to the warlock","Athanc Shard, Empower Weapon, Field Marshal: Sprint, Resonance: Everblight Warbeast, Riposte, Spawning Savant, Swift Hunter, Warlock Bond","Connections (Blighted Nyss shard), Connections (Legion of Everblight)","Archery 4, Great Weapon 4, Hand Weapon 4","Animal Handling 2, Command 4, General Skills 4", "Spells"},
        {"Deathstalker","Strider","Ambush, Prowl, Signal Language","","Archery 1 and Great Weapon 1","Sneak 1, Survival 1, Tracking 1","","","nyss bow, nyss claymore, quiver and 20 arrows, 25 gc","Ambush, Battle Plan: Coordinated Strike, Camou age, Dodger, Fleet Foot, Hunter, Night Fighter, Prowl, Signal Language, Snap Fire, Swift Hunter, Tactical Coordination, Targeteer, Tracker","Connections (Legion of Everblight)","Archery 4, Hand Weapon 3, Great Weapon 3","General Skills 4, Command 3, Cryptography 1, Sneak 4, Survival 4, Tracking 4", ""},
        {"Warmonger","Blighted Ogrun","Berserk, Fearless, Onslaught","","Unarmed Combat 1 and either Great Weapon 1 or Thrown Weapon 1","Detection 1, Intimidation 1, Survival 1","","","infantry armor and an ogrun war cleaver or 5 war spears and a war spear quiver","Abomination, Berserk, Blood Drinker, Body Slam, Dual Shot (War Spear), Fearless, Fearsome Howl, Knife Thrower, Onslaught, Quick Work, Relentless Charge, Set Defense, Specialization (Ogrun War Cleaver)","Connections (Legion of Everblight)","Thrown Weapon 4, Great Weapon 4, Unarmed Combat 4","General skills 4, Detection 4, Survival 4, Tracking 2", ""},
        {"Hex Hunter","ARC 2, Blighted Nyss, Restricted 2nd Career","Pathfinder, Specialization (Hex razor)","Connections (Legion of Everblight","Hand Weapon 1","Lore (Morrdh) 1, Sneak 1, Survival 1","Blind Spot, Hex Bolt, Hidden Path","A character who chooses Hex Hunter as one of his two starting careers gains the Blood Boon Gifted archetype benefit. A character who chooses Hex Hunter as one of his careers cannot choose the Priest of Nyssor class.","Hex razor, Nyss Leathers","Arcane consumption, Balance Out, Drain Essence, Hunter, Pathfinder, Prowl, Shadow Steel, Two-Weapon Fighting","Connections (Legion of Everblight)","Hand Weapon 4","General Skills 4, Craft (metalworking) 2, Sneak 4, Survival 3, Tracking 3", "Spells"},
        {"Blighted Sorcerer","Gifted, Blighted Nyss, Starting Career, Restricted 2nd Career","Arcane Craftsmanship","Connections (Legion of Everblight)","Choose one: Archery 1 or Hand Weapon 1","Craft (metalworking) 1, Lore (Everblight) 1","Blizzard, Howling Wind, Ice Bolt","A character who chooses Blighted sorcerer as one of his starting careers cannot choose Priest of nyssor or sorcerer as one of his other careers. a character created as a Blighted sorcerer receives the sorcerous Blessing blight gift upon character creation.","25 gc","Arcane Craftsmanship, Empower Weapon, Immunity: Cold, Language (any), Mount Attack, Saddle Shot, Spirit Tap, Trained Rider (hellion)","Connections (Legion of Everblight), Connections (Nyss Shard)","Archery 2, Great Weapon 2, Hand Weapon 2","Craft (any) 4, General Skills 4", "Spells"},
        {"Raider","Satyxis","Specialization (Lacerator)","Connections (Black Fleet)","Hand Weapon 1 and Unarmed Combat 1","Intimidation 1, Jumping 1, Sailing 1, Swimming 1","","A character starting with the Raider career must choose Cutthroat, Duelist, Gun Mage, Military Officer, Pirate, Pistoleer, Ranger, Sorcerer, or Warcaster for her other career.","Lacerator, Leather Armor","Ambush, Battle Plan: Call to Action, Boarding Action, Disease Resistance, Gang, Precision Strike, Ram, Roll with It, Specialization (Lacerator), Sprint","Connections (Black Fleet)","Hand Weapon 4, Pistol 3, Thrown Weapon 3, Unarmed Combat 4","Command 2, General Skills 4, Navigation 3, Rope Use 4, Sailing 3", ""},
        {"Blighted Swordsman","Blighted Nyss","Fearless, Flesh of Steel","","Great Weapon 1","Command 1, Intimidation 1, Survival 1","","a character created as a Blighted swordsman begins the game with the Bone spurs blight gift.","Nyss Claymore","Cleave, Combo Strike (Nyss Claymore), Fast Draw, Fearless, Flesh of Steel, Overtake, Perfect Form, Relentless Charge, Retaliatory Strike, Two-Weapon Fighting","Connections (Legion of Everblight)","Hand Weapon 2, Great Weapon 4","General Skills 4, Survival 4", ""},
                {"Shepherd","Blighted Nyss","Animal Master, Specialization (Shepherd's Crook)","","Great Weapon 1","Animal Handling 1, Survival 1, Tracking 1","","","Shepherd's Crook, 50 gc","animal Mastery, Beast Master, Beast Manipulation: Caretaker, Beast Manipulation: Enrage, Beast Manipulation: Toughen, Dodger, Specialization (Shepherd’s Crook), Wall of Flesh, Spawn Whisperer","Connections (Legion of Everblight)","Great Weapon 2","General Skills 4, Survival 4, Tracking 4", ""},
                {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
                {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
                {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
                {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
                {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
                {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},
        {"Name","Prereq","startabil","startconnect","startmili","startoccpuational","startingspels","startspecial","startassets","potentialability","potentialconnec","milit","occupationa", ""},};

        arrayList.clear();

        for (String[] ability1 : abilities) {
            Career ability = new Career(ability1[0], ability1[1], ability1[2], ability1[3], ability1[4], ability1[5], ability1[6], ability1[7], ability1[8], ability1[9], ability1[10], ability1[11], ability1[12]);
            arrayList.add(ability);
        }

        //Sorting
        Collections.sort(arrayList, new Comparator<Career>() {
            @Override
            public int compare(Career lhs, Career rhs) {
                return lhs.getName().compareTo(rhs.getName());
            }
        });

        final ListView listView = (ListView) view.findViewById(R.id.listView1);
        abilityAdapter = new CareerAdapter(getActivity(), arrayList);
        listView.setAdapter(abilityAdapter);



        final EditText myFilter = (EditText)view.findViewById(R.id.myFilter);
        myFilter.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                    String text = myFilter.getText().toString().toLowerCase(Locale.getDefault());
                    abilityAdapter.filter(text);
            }

            @Override
            public void afterTextChanged(Editable s) {

            }
        });



        return view;
    }



    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        try {
            mListener = (OnFragmentInteractionListener) activity;
        } catch (ClassCastException e) {
            throw new ClassCastException(activity.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }


    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p/>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnFragmentInteractionListener {
        // TODO: Update argument type and name
        public void onFragmentInteraction(String id);
    }



}

